language: python
sudo: false
python:
- '2.7'
- '3.5'
- '3.6'
script:
- make
notifications:
  slack: ccnmtl:GizSNscLWJLldjQrffB8mwgm
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: ctlpypi
  password:
    secure: ZUEU73xwhcy4wN5tcVXRVO2PzVi3N3SVWH/VWbHwwjDXqUNvJVYr5fLcuj187efkGrRJ2j7H33aSfHmkbVp7A7htUgIng70iY0lWx8mjfG22ud6pW8qrYU0EhgQjvWlO1zYMbWLGncSS2ZVo0WcJZxeVAB4c9DmQBHXl87nTQkR74KXWWN/LnuAkyFJdQNsRKLzxIQlqqNpreRFWJNwc01GjozEPzD3I2/liQ4+JtQr2TiByAE4/jYwqIGmBpVvPyYXyFXvY8ksptUPmoFkzpxu/Un/EdslSo1g+SWwHGqls9+NG/9pmV9dChJRd0TQO+6NSDO0FApRX81v/k2/Im2NfYMJOpMFzPiy+70Hpw+QkF2uXblujuNFzcIXAg9owTbWAiY60c/rGtn1eqbodkFk7KkZNi0HryuI2IslOHaKOmrnVfstRKvJfgD8hgJ4j5CJK4d1d3MMYBZnF2vyMtsWEGlls+rait7UzgsobLvNZ6VKn10GvBBsDZBJbihr5tDjDhwGEkuQZRuBgofdxq7rW+I9+XUlNUt7mdjx+51/BY8cZWougNwVyTkA/nwKUMhPWIssmI66YeEngsOeKmUmgZIBMU1y60j2t/tSbRM7EmX3DM0ULS3bENfX12cBy7NcNPtaaKD9ZMtdtcGLARCVoRVuHq0OE2O6PRR84qJQ=
  on:
    tags: true
    repo: ccnmtl/pypanopto
